### ISSUE TITLE
Consider using a license compatible with GPLv2

### ISSUE THREAD

**Issue by LeSuisse** [delight-im/PHP-Cookie#1]
Hi,

I would love to use this library but the current license is show stopper for me since I need to integrate it with an application under GPLv2.

Is it possible for you to re-license  or double license the library with something that does not have the same restrictions?

**Comment by mwaclawek** [comment]
Done in https://github.com/delight-im/PHP-Cookie/commit/a746f4096885b6715a640a2122b1c21324624f8f

Thank you very much for pointing this out!

Hope this helps!
