### ISSUE TITLE
Tests fail on PHP 5.x

### ISSUE THREAD

**Issue by LeSuisse** [delight-im/PHP-Cookie#11]
These 3 tests fail on PHP 5.x:
```php
testCookie(null);
testCookie(false);
testCookie('');
```

In all cases it seems that the expected value is ``Set-Cookie: =deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0`` but the library returns a empty string.

I'm not sure what have introduced the change starting PHP 7, after quick look to the changelog this bug can be related: https://bugs.php.net/bug.php?id=69523

I'm not sure how to fix this issue. Either the tests should be fixed to expect the same value in PHP 7.x and 5.x or the library should returns what PHP does.
Personally, I'm more in favor of the first solution since PHP 5.x is not conform to the RFC.

**Comment by ocram** [comment]
Thank you so much for spotting this bug!

Well, actually

```php
testCookie('my-cookie', null);
testCookie('my-cookie', false);
testCookie('my-cookie', '');
```

would produce the output

```
Set-Cookie: my-cookie=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0
```

which is expected and documented like this. If you want to delete a cookie, you should set its *value* to something "empty". But setting the name to something that is "empty" definitely seems to be undocumented behavior.

I'd say the most important goal is compatibility with PHP's built-in cookie components, so I'd argue in favor of your *second* solution. What about a switch like this in the `Cookie` class, probably at the beginning of the `buildCookieHeader` method?

```php
if (version_compare(phpversion(), '7.0.0', '>=')) {
    // current behavior for invalid names
}
else {
    // accept invalid names as empty strings
}
```

**Comment by ocram** [comment]
Thanks again!

Resolved in https://github.com/delight-im/PHP-Cookie/pull/13
