### ISSUE TITLE
Incompatible with CSRF protection

### ISSUE THREAD

**Issue by ponasromas** [delight-im/PHP-Cookie#15]
Hello,

PHP-Cookie is not comaptible with https://wiki.php.net/rfc/automatic_csrf_protection . 

It is not possible to set:

`session_start(['csrf_rewrite'=>SESSION_CSRF_POST, 'csrf_validate'=>SESSION_CSRF_POST]);`

Due to "Session already" started. Any workarounds?

**Comment by ocram** [comment]
Thanks for your feedback!

That RFC which you linked to has not been accepted into PHP yet, has it?

As far as I can see, it is just a *proposal* of a new feature that *might* be added in the future. Furthermore, it is only a *draft* so far, which has not been (and cannot be) voted on yet.

As soon as something like this becomes available in a release of PHP, this library will support it, of course.

By the way, already today, you have built-in CSRF protection in this library for

 * Chrome on desktop
 * Chrome on Android
 * Opera on desktop
 * Opera on Android
 * WebView on Android

without any additional effort. That's not enough, unfortunately, but the best you can get today without any custom solution. Until browser support improves here (or until that RFC is accepted into PHP), it seems you have to implement a custom CSRF protection as per common practices.
