### ISSUE TITLE
Suggest to implement getCookie.

### ISSUE THREAD

**Issue by shtse8** [delight-im/PHP-Cookie#18]
I know we can get cookie using `$_COOKIE`, but it is much better we can get the cookie using this project. so we can manage all cookies using this library.

**Comment by ocram** [comment]
Thanks!

That makes sense, and it will not be much code, so it won’t be too much overhead for those who don’t want to use it.

What about the following two static methods?

```php
Cookie::exists('my_cookie_name');

// and

Cookie::get('my_cookie_name');
// or
Cookie::get('my_cookie_name', $myDefaultValue);
```

**Comment by shtse8** [comment]
```
Cookie::exists('my_cookie_name');
```
```
Cookie::get('my_cookie_name');
```

I think default value should be handled by developers. not by his project.

**Comment by ocram** [comment]
Given that the parameter for the default value will be optional, anyway, I don’t see any problem with that. The other syntax is not available yet for everybody, but will soon be, of course. So then everybody will be able to just use the syntax they prefer.

**Comment by ocram** [comment]
Implemented in:

 * https://github.com/delight-im/PHP-Cookie/commit/c1a50c1a98f1c20ba274a95aa9bbab2cb95471de
 * https://github.com/delight-im/PHP-Cookie/commit/ab98e92766a6e806ea08df47f205e13b2dd531e8
 * https://github.com/delight-im/PHP-Cookie/commit/99e95650fccdc97e8714e14631edb665ae4c8751
