### ISSUE TITLE
id() not compatible with session_id()

### ISSUE THREAD

**Issue by Synchro** [delight-im/PHP-Cookie#2]
The built-in `session_id()` function takes an optional ID parameter; the `Session::id()` wrapper method does not, so will break in some circumstances if you try to use `Session::id` as a drop in replacement for `session_id`.

**Comment by mwaclawek** [comment]
Oh, I must have missed that!

Thank you so much for pointing this out. Please see https://github.com/delight-im/PHP-Cookie/pull/3 for the merged pull request.
