### ISSUE TITLE
Cookie Parse Error

### ISSUE THREAD

**Issue by Lednerb** [delight-im/PHP-Cookie#20]
Hello,

I'm using this library to simplify my tests for cookies that have set the `secure` and `httpOnly` flags.

However, regarding this specification, only the `cookiename=value` is required, all other directives are optional:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#Directives

When I'm using:

```
$cookie = Cookie::parse("Set-Cookie: session=myCookie");
$cookie->isSecureOnly();
```

I get the following error:
```
Error: Call to a member function isSecureOnly() on null
```

Same with `$cookie->isHttpOnly()`.

--------------------------------------

There is an error in this regex, I think:
https://github.com/delight-im/PHP-Cookie/blob/master/src/Cookie.php#L380

**Comment by ocram** [comment]
Thank you very much!

Fixed in https://github.com/delight-im/PHP-Cookie/commit/deecb7d2f5a27a17ad2f89b58d3130ee72272ef4.

**Comment by Lednerb** [comment]
Thank you for your fast support.
