### ISSUE TITLE
Consider droping PHP 5 and 7.0.

### ISSUE THREAD

**Issue by omatamix** [delight-im/PHP-Cookie#23]
PHP Roadmap.
- http://php.net/supported-versions.php

**Comment by ocram** [comment]
Thanks!

We don’t just drop support for PHP versions as soon as we can. We only do so if some version holds us back or is really not used anymore in practice.

So are there any specific reasons for this request?

**Comment by omatamix** [comment]
I just strongly recommend it considering why support PHP 5 syntax when it should not be used. Plus if you support PHP 5 you can not use any of PHP >= 7.1 features. It just seems to be a time waster to support PHP 5 and 7.0. What i suggest is the next major version just drop PHP 5 and PHP 7.0.

**Comment by ocram** [comment]
Well, yes, but the whole library *is* already compliant with the old syntax *today*, and PHP 7.0 (and even PHP 5) are definitely still being used outside there. For example, they come pre-packaged with several Linux distributions.

But we’ll drop them as soon as it’s the right time for that, which should be soon.

Thanks again!
