### ISSUE TITLE
[Question] How to set array in session

### ISSUE THREAD

**Issue by ponasromas** [delight-im/PHP-Cookie#30]
It looks like simple task, but with this library I'am not sure how to do that. Here is my code:

```
if (is_array($text)) {
   // what's the correct way to add array to a session? array_push?

 } else {
    \Delight\Cookie\Session::set('text', "$text");
}
```

In plain world you add array into session like this:

```
$_SESSION['names'] = array();
array_push($_SESSION['names'],$name);
```

**Comment by ocram** [comment]
Thanks!

Is there any reason why

```php
$names = [ 'John', 'Jane' ];
\Delight\Cookie\Session::set('names', $names);
```

does not work?

**Comment by ponasromas** [comment]
Indeed it works when I removed those quotes "". What a shame! Thank you Ocram, you saved my day :)
