### ISSUE TITLE
Trouble setting `SameSite=None` cookie for cross-domain requests

### ISSUE THREAD

**Issue by IliasDeros** [delight-im/PHP-Cookie#33]
Hi, great library! 

Using `PHP 5.6`, I had trouble setting `SameSite=None` for the session cookie , so I'm documenting this workaround in case anyone else struggles.

If possible, please comment a more efficient way to do this.

## Workaround
Before sending out the login response, get the cookie and add `SameSite=None` to it

```
\ini_set('session.cookie_httponly', 1);
\ini_set('session.cookie_secure', 1);
\ini_set('session.name', 'delight_session');

// https://stackoverflow.com/questions/3230133/accessing-cookie-immediately-after-setcookie#34465594
function getcookie($name) {
    $cookies = [];
    $headers = headers_list();

    // see http://tools.ietf.org/html/rfc6265#section-4.1.1
    foreach($headers as $header) {
        if (strpos($header, 'Set-Cookie: ') === 0) {
            $value = str_replace('&', urlencode('&'), substr($header, 12));
            parse_str(current(explode(';', $value, 1)), $pair);
            $cookies = array_merge_recursive($cookies, $pair);
        }
    }

    return $cookies[$name];
}

function withoutSamesite($cookie) {
    $samesitePattern = '/samesite=[^;]+;?/i';
    return preg_replace($samesitePattern, '', $cookie);
}

function setcookieSamesite($cookieName, $samesiteValue) {
    $existingCookie = getcookie($cookieName);
    $cookie = withoutSamesite($existingCookie);
    $cookieSamesite = "$cookie ; SameSite=$samesiteValue";

    header("Set-Cookie: $cookieName=$cookieSamesite");
}

$auth->login($email, $password);
set_cookie_samesite("delight_session", "None");
```

## Results
✅The session cookie can now be sent across domains in Chrome browsers

![image](https://user-images.githubusercontent.com/9534435/202230560-8c74a7de-f8bd-4497-9ec5-108c12a51f83.png)

**Comment by informatik-handwerk** [comment]
Here [a few other inspirative ways](https://stackoverflow.com/a/59009264), with the accepted hack of piggibacking it onto path parameter `"$path; samesite=strict"` and magically working, I can only confirm, no escaping on path seems to be taking place.
