### ISSUE TITLE
Constructor's parameter order

### ISSUE THREAD

**Issue by GregMartyn** [delight-im/PHP-Cookie#4]
The constructor's parameter list is mostly the same as setcookie(), with the exception of httpOnly and secureOnly, which are swapped. Would you consider swapping them in a future version so that they align with setcookie()?

I was porting some code that was using setcookie() to using the PHP-Cookie constructor and noticed that it's very easy to miss that.

**Comment by mwaclawek** [comment]
Thanks a lot for your feedback on this!

What method's signature are you talking about, exactly?

The `Cookie::setcookie(...)` method, which has been added as a replacement for PHP's native function of the same name, is fully compatible with the PHP function, as you can see [here](https://github.com/delight-im/PHP-Cookie/blob/004cde69ec840e65c15275e09b92ecb1da06f357/src/Cookie.php#L200).

The constructor, on the other hand, has only *one* parameter, which is the cookie's name, as you can see [here](https://github.com/delight-im/PHP-Cookie/blob/004cde69ec840e65c15275e09b92ecb1da06f357/src/Cookie.php#L51). All the other attributes on instances are set via the setters which cannot really be mixed up, right?

**Comment by GregMartyn** [comment]
Oh, oops, you're right. I saw it doing $this->name = ... $this->value = ... etc and I guess I assumed the constructor was being passed all those parameters in order. Nothing to see here..

**Comment by mwaclawek** [comment]
No problem, thank you!
