### ISSUE TITLE
Add getters for cookie properties

### ISSUE THREAD

**Issue by Suseika** [delight-im/PHP-Cookie#9]
There are use cases where you'd want that. For example, mine is: I parse a cookie from a `Set-Cookie:` header, and then, before saving it, I need to check if it has an `expires` or not. Currently it is not possible with your library. It could look like this:

```php
$cookie = Cookie::parse($setCookieHttpHeader);
if ($cookie->getExpires() == null) {
  modifyCookieInSomeWay($cookie);
}
$cookie->save();
```

I get it that hiding data is a good OOP practice, but I think that data should not be hidden.

**Comment by ocram** [comment]
> There are use cases where you'd want that.

Absolutely, I agree! And the case you mentioned is an important (and probably common) one.

> I get it that hiding data is a good OOP practice, but I think that data should not be hidden.

No, your proposal definitely makes sense and we will add this as soon as possible.

Thanks for this important hint!

**Comment by ocram** [comment]
Thanks again!

This has been implemented in https://github.com/delight-im/PHP-Cookie/commit/4f95f1c15f84db7f896449805cacb880bee148e0 and https://github.com/delight-im/PHP-Cookie/commit/3e41e0d44959b59de98722b5b1b1fb83f9f528f3 now.

Please update your Composer dependency to make use of these changes.

Hope that helps :)
